import { test, expect } from '@playwright/test'

test('allow signup and login', async ({ page }) => {
  const testUser = 'test' + Date.now()
  await page.goto('/')
  await page.getByRole('link', { name: 'Sign up' }).click()
  await page.getByLabel('Username:').click()
  await page.getByLabel('Username:').fill(testUser)
  await page.getByLabel('Username:').press('Tab')
  await page.getByLabel('Password:').fill('test')
  await page.getByRole('button', { name: 'Sign up' }).click()
  await page.waitForURL('**/login')
  await page.getByLabel('Username:').click()
  await page.getByLabel('Username:').fill(testUser)
  await page.getByLabel('Username:').press('Tab')
  await page.getByLabel('Password:').fill('test')
  await page.getByRole('button', { name: 'Log in' }).click()
  await page.waitForURL('**/')
  await expect(page.locator('nav')).toContainText('Logged in as ' + testUser)
})
